# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ 
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ 
    "xhci_pci" 
    "ahci" 
    "usbhid" 
    "usb_storage" 
    "sd_mod" 
    "sdhci_pci" 
  ];

  boot.kernelModules = [ "kvm-intel" ];
  boot.initrd.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = { 
    device = "/dev/disk/by-uuid/a06168ce-2d2c-426f-b655-c2f1fc7e6fca";
    fsType = "ext4";
  };
 
  fileSystems."/mnt/s/" = {
    device = "/dev/disk/by-label/s";
  };

  fileSystems."/boot" = { 
    device = "/dev/disk/by-uuid/EE90-B316";
    fsType = "vfat";
  };

  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
